repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-yaml
    exclude: results
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: local
  hooks:
    - id: isort
      name: isort
      entry: poetry run isort --settings-path pyproject.toml
      types: [python]
      language: system
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
- repo: https://github.com/asottile/pyupgrade
  rev: v3.1.0
  hooks:
    - id: pyupgrade
- repo: https://github.com/flakeheaven/flakeheaven
  rev: 3.0.0  # pick a git hash / tag to point to
  hooks:
  - id: flakeheaven
    exclude: "^data_augmentation/myrtle.*|^data_augmentation/quantum_blur.py"
- repo: https://github.com/pycqa/pydocstyle
  rev: 6.1.1  # pick a git hash / tag to point to
  hooks:
  - id: pydocstyle
    additional_dependencies: ["pydocstyle[toml]"]
    exclude: "^data_augmentation/myrtle.*|^data_augmentation/quantum_blur.py"
